version: 2.1

jobs:
  testing:
    docker:
      - image: quay.io/pypa/manylinux1_i686
    steps:
      - checkout
      - run:
          name: Install dependencies for Python 3.7
          command: /opt/python/cp37-cp37m/bin/pip install astropy numpy scipy matplotlib pytest pytest-astropy pytest-xdist Cython jinja2
      - run:
          name: Run tests for Python 3.7
          command: PYTHONHASHSEED=42 /opt/python/cp37-cp37m/bin/python testing_SB2.py "--durations=50"

workflows:
  version: 2.1
  tests_and_docs:
    jobs:
      - testing

notify:
  webhooks:
    - url: https://giles.cadair.com/circleci 