version: 2.1

jobs:
  testing:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install Python 3.7.3 dependicies 
          command: |  #Install Python deps in a venv
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - run:
          name: Run tests for Python 3.7
          command: |
            . venv/bin/activate
            python3 testing_SB2.py

  flake8-test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install Python 3.7.3 dependicies
          command: |  #Install Python deps in a venv
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - run:
          name: Run flake8
          command: |
            . venv/bin/activate
            flake8 .

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - testing
      - flake8-test
