version: 2

jobs:
  testing:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          command: |  #Install Python deps in a venv
            python3 -m venv venv
            . venv/bin/activate
            pip install astropy numpy scipy matplotlib pytest pytest-astropy pytest-xdist Cython jinja2
      - run:
          name: Run tests for Python 3.7
          command: python3 testing_SB2.py "--durations=50"

workflows:
  version: 2
  build_and_test:
    jobs:
      - testing
